import { 
  RefreshCw, 
  Save, 
  X, 
  RotateCcw, 
  FileText, 
  Settings, 
  DollarSign,
  Recycle,
  Clock,
  Zap,
  Wrench,
  TrendingUp,
  TrendingDown
} from 'lucide-react';

export const DEFAULT_PARAMETERS = {
  pricePerKg: 100,
  pricePerHour: 2,
  flatWorkFee: 3,
  electricityConsumption: 150,
  electricityPrice: 1.5,
  markup: 20,
};

export const DEFAULT_ENABLED = {
  pricePerKg: true,
  pricePerHour: true,
  flatWorkFee: true,
  electricityConsumption: true,
  electricityPrice: true,
  markup: true,
};

export const UI_TEXT = {
  COMMON: {
    PRINT_BUTTON: 'Print',
    SAVE_BUTTON: 'Save',
    CANCEL_BUTTON: 'Cancel',
    RESET_BUTTON: 'Default',
  },
  WORK_DETAILS: {
    TITLE: 'File Details',
    PRINT_TITLE: '3D Printing Cost Calculation',
    FILAMENT_WEIGHT: 'Filament Weight',
    PRINT_TIME: 'Print Time',
    OPEN_GCODE: 'Open G-code',
  },
  PARAMETERS: {
    TITLE: 'Parameters',
    EDIT_BUTTON: 'Edit',
    PER_KG: 'Price per kg',
    PER_HOUR: 'Price per hour',
    WORK_FEE: 'Maintenance fee',
    ELECTRICITY_CONSUMPTION: 'Power consumption',
    ELECTRICITY_PRICE: 'Power price',
    MARKUP: 'Markup',
    DISCOUNT: 'Discount',
  },
  COST_DETAILS: {
    TITLE: 'Price Details',
    TOTAL_COST: 'Final Cost',
    MATERIAL_COST: 'Material cost',
    TIME_COST: 'Time cost',
    ELECTRICITY_COST: 'Power cost',
    WORK_FEE: 'Maintenance fee',
    SUBTOTAL: 'Subtotal',
    MARKUP_LABEL: (value: number) => `Markup (${value}%):`,
    DISCOUNT_LABEL: (value: number) => `Discount (${value}%):`,
    TOTAL: 'Total',
    SHOW_DETAILS: 'View full details',
  },
  VALIDATION: {
    POSITIVE_NUMBER: 'Enter a positive number',
    MINUTES_RANGE: 'Between 0 and 59 minutes',
  },
  TOAST: {
    GCODE_INVALID: 'Missing metadata in G-code file',
    GCODE_ERROR: 'Error processing G-code file',
    PARAMS_SAVED: 'Parameters saved successfully',
    MODIFY_PARAMS: 'Modify Print Parameters',
  },
  PARAMETER_LABELS: {
    PRICE_PER_KG: 'Price per kg',
    PRICE_PER_HOUR: 'Price per hour',
    FLAT_WORK_FEE: 'Maintenance fee',
    ELECTRICITY_CONSUMPTION: 'Power consumption',
    ELECTRICITY_PRICE: 'Power cost',
    MARKUP: 'Markup',
    DISCOUNT: 'Discount',
  },
  COST_BREAKDOWN: {
    MATERIAL_COST: 'Material cost',
    TIME_COST: 'Time cost',
    ELECTRICITY_COST: 'Power cost',
    WORK_FEE: 'Maintenance fee',
  },
  UNITS: {
    GRAMS: 'g',
    HOURS: 'hrs',
    MINUTES: 'min',
    PER_KG: 'RON/kg',
    PER_HOUR: 'RON/h',
    WORK_FEE: 'RON',
    ELECTRICITY: 'W',
    ELECTRICITY_PRICE: 'RON/kWh',
    PERCENT: '%',
  },
  ICONS: {
    MATERIAL: Recycle,
    TIME: Clock,
    ELECTRICITY: Zap,
    WORK: Wrench,
    MARKUP_UP: TrendingUp,
    MARKUP_DOWN: TrendingDown,
  },
};
