export const DEFAULT_PARAMETERS = {
  pricePerKg: 100,
  pricePerHour: 2,
  flatWorkFee: 3,
  electricityConsumption: 150,
  electricityPrice: 1.5,
  markup: 20,
};

export const DEFAULT_ENABLED = {
  pricePerKg: true,
  pricePerHour: true,
  flatWorkFee: true,
  electricityConsumption: true,
  electricityPrice: true,
  markup: true,
};

export const UI_TEXT = {
  COMMON: {
    PRINT_BUTTON: 'Print',
    SAVE_BUTTON: 'Save',
    CANCEL_BUTTON: 'Cancel',
    RESET_BUTTON: 'Default',
  },
  WORK_DETAILS: {
    TITLE: 'File Details',
    PRINT_TITLE: '3D Printing Cost Calculation',
    FILAMENT_WEIGHT: 'Filament Weight',
    PRINT_TIME: 'Print Time',
    OPEN_GCODE: 'Open G-code',
  },
  PARAMETERS: {
    TITLE: 'Parameters',
    EDIT_BUTTON: 'Edit',
    PER_KG: 'Price per kg',
    PER_HOUR: 'Price per hour',
    WORK_FEE: 'Maintenance fee',
    ELECTRICITY_CONSUMPTION: 'Power consumption',
    ELECTRICITY_PRICE: 'Power price',
    MARKUP: 'Markup',
  },
  COST_DETAILS: {
    TITLE: 'Price Details',
    TOTAL_COST: 'Final Cost',
    MATERIAL_COST: 'Material cost:',
    TIME_COST: 'Time cost:',
    ELECTRICITY_COST: 'Power cost:',
    WORK_FEE: 'Maintenance fee:',
    SUBTOTAL: 'Subtotal:',
    MARKUP_LABEL: (value: number) => `Markup (${value}%):`,
    TOTAL: 'Total:',
    SHOW_DETAILS: 'View full details',
  },
  VALIDATION: {
    POSITIVE_NUMBER: 'Enter a positive number',
    MINUTES_RANGE: 'Between 0 and 59 minutes',
  },
  TOAST: {
    GCODE_PARSER: 'G-code parsing not implemented yet',
    GCODE_DESCRIPTION: 'This feature will extract weight and print time from G-code files',
    PARAMS_SAVED: 'Parameters saved successfully',
    MODIFY_PARAMS: 'Modify Print Parameters',
  },
  PARAMETER_LABELS: {
    PRICE_PER_KG: 'Price per kg',
    PRICE_PER_HOUR: 'Price per hour',
    FLAT_WORK_FEE: 'Flat work fee',
    ELECTRICITY_CONSUMPTION: 'Electricity consumption',
    ELECTRICITY_PRICE: 'Electricity price',
    MARKUP: 'Markup percentage',
  },
  COST_BREAKDOWN: {
    MATERIAL_COST: 'Material cost:',
    TIME_COST: 'Time cost:',
    ELECTRICITY_COST: 'Electricity cost:',
    WORK_FEE: 'Work fee:',
  },
  UNITS: {
    GRAMS: 'g',
    HOURS: 'hrs',
    MINUTES: 'min',
    PER_KG: 'lei/kg',
    PER_HOUR: 'lei/h',
    WORK_FEE: 'lei',
    ELECTRICITY: 'W',
    ELECTRICITY_PRICE: 'lei/kWh',
    PERCENT: '%',
  },
};
